//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorDetail
    {
        public int DonorId { get; set; }
        public string DonorName { get; set; }
        public string DonorAddress { get; set; }
        public string DonorEmail { get; set; }
        public string DonorMobile { get; set; }
        public string DonorGender { get; set; }
        public string OrganName { get; set; }
        public Nullable<bool> IsHospitalAuthorized { get; set; }
    }
}
