//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonorEntities : DbContext
    {
        public DonorEntities()
            : base("name=DonorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<DonorDetail> DonorDetails { get; set; }
        public virtual DbSet<CheckUp> CheckUps { get; set; }
        public virtual DbSet<BloodDonation> BloodDonations { get; set; }
    }
}
